version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: idssapp
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: teachers_hub
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    build: ./server
    environment:
      DATABASE_URL: postgres://idssapp:strongpassword@db:5432/teachers_hub
      JWT_SECRET: supersecret_jwt
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
volumes:
  db_data: